name: Deploy Farcaster-friendly Repo Page
on:
  push:
    branches:
      - main
    paths:
      - "README.md"
  pull_request:
    branches:
      - main
    paths:
      - "README.md"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Farcaster-friendly Page
        uses: vrypan/gh-frame@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Default GitHub token
          style: light  # or dark/custom
          # Optionally set cname or branch_name if you want:
          # cname: yourdomain.com
          # branch_name: gh-pages
